### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by fermin96** [MOZGIII/ue4-gitignore#2]
Hello, I'm new to UE4, if you could help me and upload the program or send it to me it would be very helpful, the problem is that in my country it can not be downloaded and I'm really interested.

**Comment by MOZGIII** [comment]
Sorry, can't help with that. You can just google UE4, I'm sure there's plenty of places you can get it from. You should also consider using VPN if you have connectivity issues to official Epic's server - this may help.
